/* Automatically generated by './build/bin/build-entry.js' */

import { CustomEventPlugin } from '@sinokit/utils';
import JsonEditor from './json-editor/index.js';
import OverviewTimeline from './overview-timeline/index.js';
import QueryTags from './query-tags/index.js';
import CountDown from './count-down/index.js';
import Result from './result/index.js';
import Ellipsis from './ellipsis/index.js';
import NumberInfo from './number-info/index.js';
import Sticky from './sticky/index.js';
import BacktoTop from './backto-top/index.js';
import FullScreen from './full-screen/index.js';

const components = [
  JsonEditor,
  OverviewTimeline,
  QueryTags,
  CountDown,
  Result,
  Ellipsis,
  NumberInfo,
  Sticky,
  BacktoTop,
  FullScreen
];

const install = function(Vue) {
  Vue.use(CustomEventPlugin);

  components.forEach(component => {
    Vue.component(component.name, component);
  });


};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
<<<<<<< HEAD
  version: '0.2.11',
=======
  version: '0.3.1',
>>>>>>> master
  install,
  JsonEditor,
  OverviewTimeline,
  QueryTags,
  CountDown,
  Result,
  Ellipsis,
  NumberInfo,
  Sticky,
  BacktoTop,
  FullScreen
};
