var Modules = require('./files.json');
var fs = require('fs');
var render = require('json-templater/string');
var uppercamelcase = require('uppercamelcase');
var path = require('path');
var endOfLine = require('os').EOL;

var OUTPUT_PATH = path.join(__dirname, './index.js');
var IMPORT_TEMPLATE = "import * as {{name}} from '{{path}}';";
var INSTALL_COMPONENT_TEMPLATE = '  {{name}}';
var MAIN_TEMPLATE = `/* Automatically generated by './build-entry.js' */

{{include}}

export default {
  version: '{{version}}',
{{module}}
};
`;

var ModulesNames = Object.keys(Modules);

var includeComponentTemplate = [];
var installTemplate = [];

ModulesNames.forEach(name => {
  var modulesNames = uppercamelcase(name);

  includeComponentTemplate.push(
    render(IMPORT_TEMPLATE, {
      name: modulesNames,
      package: name,
      path: Modules[name]
    })
  );
  installTemplate.push(
    render(INSTALL_COMPONENT_TEMPLATE, {
      name: modulesNames,
      component: name
    })
  );
});

var template = render(MAIN_TEMPLATE, {
  include: includeComponentTemplate.join(endOfLine),
  module: installTemplate.join(',' + endOfLine),
  version: process.env.VERSION || require('./package.json').version
});

fs.writeFileSync(OUTPUT_PATH, template);
console.log('[build entry] DONE:', OUTPUT_PATH);
